/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFtsoGenesis,
  IFtsoGenesisInterface,
} from "../../../../../../@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoGenesis";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_voter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_epochId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_wNatVP",
        type: "uint256",
      },
    ],
    name: "revealPriceSubmitter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_voter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_epochId",
        type: "uint256",
      },
    ],
    name: "wNatVotePowerCached",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFtsoGenesis__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoGenesisInterface {
    return new Interface(_abi) as IFtsoGenesisInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFtsoGenesis {
    return new Contract(address, _abi, runner) as unknown as IFtsoGenesis;
  }
}
