/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFtsoGenesis__factory } from "./IFtsoGenesis__factory";
export { IFtsoManagerGenesis__factory } from "./IFtsoManagerGenesis__factory";
export { IFtsoRegistryGenesis__factory } from "./IFtsoRegistryGenesis__factory";
