/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IICleanable } from "./IICleanable";
export type { IIGovernanceVotePower } from "./IIGovernanceVotePower";
export type { IIVPContract } from "./IIVPContract";
export type { IIVPToken } from "./IIVPToken";
