/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IFtsoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "active"
      | "getCurrentEpochId"
      | "getCurrentPrice"
      | "getCurrentPriceDetails"
      | "getCurrentPriceFromTrustedProviders"
      | "getCurrentPriceWithDecimals"
      | "getCurrentPriceWithDecimalsFromTrustedProviders"
      | "getCurrentRandom"
      | "getEpochId"
      | "getEpochPrice"
      | "getEpochPriceForVoter"
      | "getPriceEpochConfiguration"
      | "getPriceEpochData"
      | "getRandom"
      | "symbol"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LowTurnout"
      | "PriceEpochInitializedOnFtso"
      | "PriceFinalized"
      | "PriceRevealed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "active", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentEpochId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPriceDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPriceFromTrustedProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPriceWithDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPriceWithDecimalsFromTrustedProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRandom",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochPriceForVoter",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceEpochConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceEpochData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRandom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;

  decodeFunctionResult(functionFragment: "active", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentEpochId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPriceDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPriceFromTrustedProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPriceWithDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPriceWithDecimalsFromTrustedProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEpochId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEpochPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEpochPriceForVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceEpochConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceEpochData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRandom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
}

export namespace LowTurnoutEvent {
  export type InputTuple = [
    epochId: BigNumberish,
    natTurnout: BigNumberish,
    lowNatTurnoutThresholdBIPS: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    epochId: bigint,
    natTurnout: bigint,
    lowNatTurnoutThresholdBIPS: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    epochId: bigint;
    natTurnout: bigint;
    lowNatTurnoutThresholdBIPS: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceEpochInitializedOnFtsoEvent {
  export type InputTuple = [
    epochId: BigNumberish,
    endTime: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    epochId: bigint,
    endTime: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    epochId: bigint;
    endTime: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceFinalizedEvent {
  export type InputTuple = [
    epochId: BigNumberish,
    price: BigNumberish,
    rewardedFtso: boolean,
    lowIQRRewardPrice: BigNumberish,
    highIQRRewardPrice: BigNumberish,
    lowElasticBandRewardPrice: BigNumberish,
    highElasticBandRewardPrice: BigNumberish,
    finalizationType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    epochId: bigint,
    price: bigint,
    rewardedFtso: boolean,
    lowIQRRewardPrice: bigint,
    highIQRRewardPrice: bigint,
    lowElasticBandRewardPrice: bigint,
    highElasticBandRewardPrice: bigint,
    finalizationType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    epochId: bigint;
    price: bigint;
    rewardedFtso: boolean;
    lowIQRRewardPrice: bigint;
    highIQRRewardPrice: bigint;
    lowElasticBandRewardPrice: bigint;
    highElasticBandRewardPrice: bigint;
    finalizationType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceRevealedEvent {
  export type InputTuple = [
    voter: AddressLike,
    epochId: BigNumberish,
    price: BigNumberish,
    timestamp: BigNumberish,
    votePowerNat: BigNumberish,
    votePowerAsset: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    epochId: bigint,
    price: bigint,
    timestamp: bigint,
    votePowerNat: bigint,
    votePowerAsset: bigint
  ];
  export interface OutputObject {
    voter: string;
    epochId: bigint;
    price: bigint;
    timestamp: bigint;
    votePowerNat: bigint;
    votePowerAsset: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFtso extends BaseContract {
  connect(runner?: ContractRunner | null): IFtso;
  waitForDeployment(): Promise<this>;

  interface: IFtsoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  active: TypedContractMethod<[], [boolean], "view">;

  getCurrentEpochId: TypedContractMethod<[], [bigint], "view">;

  getCurrentPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _timestamp: bigint }],
    "view"
  >;

  getCurrentPriceDetails: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _price: bigint;
        _priceTimestamp: bigint;
        _priceFinalizationType: bigint;
        _lastPriceEpochFinalizationTimestamp: bigint;
        _lastPriceEpochFinalizationType: bigint;
      }
    ],
    "view"
  >;

  getCurrentPriceFromTrustedProviders: TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _timestamp: bigint }],
    "view"
  >;

  getCurrentPriceWithDecimals: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _price: bigint;
        _timestamp: bigint;
        _assetPriceUsdDecimals: bigint;
      }
    ],
    "view"
  >;

  getCurrentPriceWithDecimalsFromTrustedProviders: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _price: bigint;
        _timestamp: bigint;
        _assetPriceUsdDecimals: bigint;
      }
    ],
    "view"
  >;

  getCurrentRandom: TypedContractMethod<[], [bigint], "view">;

  getEpochId: TypedContractMethod<[_timestamp: BigNumberish], [bigint], "view">;

  getEpochPrice: TypedContractMethod<
    [_epochId: BigNumberish],
    [bigint],
    "view"
  >;

  getEpochPriceForVoter: TypedContractMethod<
    [_epochId: BigNumberish, _voter: AddressLike],
    [bigint],
    "view"
  >;

  getPriceEpochConfiguration: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _firstEpochStartTs: bigint;
        _submitPeriodSeconds: bigint;
        _revealPeriodSeconds: bigint;
      }
    ],
    "view"
  >;

  getPriceEpochData: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        _epochId: bigint;
        _epochSubmitEndTime: bigint;
        _epochRevealEndTime: bigint;
        _votePowerBlock: bigint;
        _fallbackMode: boolean;
      }
    ],
    "view"
  >;

  getRandom: TypedContractMethod<[_epochId: BigNumberish], [bigint], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "active"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCurrentEpochId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPriceDetails"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _price: bigint;
        _priceTimestamp: bigint;
        _priceFinalizationType: bigint;
        _lastPriceEpochFinalizationTimestamp: bigint;
        _lastPriceEpochFinalizationType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPriceFromTrustedProviders"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPriceWithDecimals"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _price: bigint;
        _timestamp: bigint;
        _assetPriceUsdDecimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPriceWithDecimalsFromTrustedProviders"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _price: bigint;
        _timestamp: bigint;
        _assetPriceUsdDecimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentRandom"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEpochId"
  ): TypedContractMethod<[_timestamp: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEpochPrice"
  ): TypedContractMethod<[_epochId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEpochPriceForVoter"
  ): TypedContractMethod<
    [_epochId: BigNumberish, _voter: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceEpochConfiguration"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _firstEpochStartTs: bigint;
        _submitPeriodSeconds: bigint;
        _revealPeriodSeconds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceEpochData"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        _epochId: bigint;
        _epochSubmitEndTime: bigint;
        _epochRevealEndTime: bigint;
        _votePowerBlock: bigint;
        _fallbackMode: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRandom"
  ): TypedContractMethod<[_epochId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LowTurnout"
  ): TypedContractEvent<
    LowTurnoutEvent.InputTuple,
    LowTurnoutEvent.OutputTuple,
    LowTurnoutEvent.OutputObject
  >;
  getEvent(
    key: "PriceEpochInitializedOnFtso"
  ): TypedContractEvent<
    PriceEpochInitializedOnFtsoEvent.InputTuple,
    PriceEpochInitializedOnFtsoEvent.OutputTuple,
    PriceEpochInitializedOnFtsoEvent.OutputObject
  >;
  getEvent(
    key: "PriceFinalized"
  ): TypedContractEvent<
    PriceFinalizedEvent.InputTuple,
    PriceFinalizedEvent.OutputTuple,
    PriceFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "PriceRevealed"
  ): TypedContractEvent<
    PriceRevealedEvent.InputTuple,
    PriceRevealedEvent.OutputTuple,
    PriceRevealedEvent.OutputObject
  >;

  filters: {
    "LowTurnout(uint256,uint256,uint256,uint256)": TypedContractEvent<
      LowTurnoutEvent.InputTuple,
      LowTurnoutEvent.OutputTuple,
      LowTurnoutEvent.OutputObject
    >;
    LowTurnout: TypedContractEvent<
      LowTurnoutEvent.InputTuple,
      LowTurnoutEvent.OutputTuple,
      LowTurnoutEvent.OutputObject
    >;

    "PriceEpochInitializedOnFtso(uint256,uint256,uint256)": TypedContractEvent<
      PriceEpochInitializedOnFtsoEvent.InputTuple,
      PriceEpochInitializedOnFtsoEvent.OutputTuple,
      PriceEpochInitializedOnFtsoEvent.OutputObject
    >;
    PriceEpochInitializedOnFtso: TypedContractEvent<
      PriceEpochInitializedOnFtsoEvent.InputTuple,
      PriceEpochInitializedOnFtsoEvent.OutputTuple,
      PriceEpochInitializedOnFtsoEvent.OutputObject
    >;

    "PriceFinalized(uint256,uint256,bool,uint256,uint256,uint256,uint256,uint8,uint256)": TypedContractEvent<
      PriceFinalizedEvent.InputTuple,
      PriceFinalizedEvent.OutputTuple,
      PriceFinalizedEvent.OutputObject
    >;
    PriceFinalized: TypedContractEvent<
      PriceFinalizedEvent.InputTuple,
      PriceFinalizedEvent.OutputTuple,
      PriceFinalizedEvent.OutputObject
    >;

    "PriceRevealed(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PriceRevealedEvent.InputTuple,
      PriceRevealedEvent.OutputTuple,
      PriceRevealedEvent.OutputObject
    >;
    PriceRevealed: TypedContractEvent<
      PriceRevealedEvent.InputTuple,
      PriceRevealedEvent.OutputTuple,
      PriceRevealedEvent.OutputObject
    >;
  };
}
