/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IFtsoInflationConfigurations {
  export type FtsoConfigurationStruct = {
    feedIds: BytesLike;
    inflationShare: BigNumberish;
    minRewardedTurnoutBIPS: BigNumberish;
    primaryBandRewardSharePPM: BigNumberish;
    secondaryBandWidthPPMs: BytesLike;
    mode: BigNumberish;
  };

  export type FtsoConfigurationStructOutput = [
    feedIds: string,
    inflationShare: bigint,
    minRewardedTurnoutBIPS: bigint,
    primaryBandRewardSharePPM: bigint,
    secondaryBandWidthPPMs: string,
    mode: bigint
  ] & {
    feedIds: string;
    inflationShare: bigint;
    minRewardedTurnoutBIPS: bigint;
    primaryBandRewardSharePPM: bigint;
    secondaryBandWidthPPMs: string;
    mode: bigint;
  };
}

export interface IFtsoInflationConfigurationsInterface extends Interface {
  getFunction(
    nameOrSignature: "getFtsoConfiguration" | "getFtsoConfigurations"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFtsoConfiguration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFtsoConfigurations",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getFtsoConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFtsoConfigurations",
    data: BytesLike
  ): Result;
}

export interface IFtsoInflationConfigurations extends BaseContract {
  connect(runner?: ContractRunner | null): IFtsoInflationConfigurations;
  waitForDeployment(): Promise<this>;

  interface: IFtsoInflationConfigurationsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFtsoConfiguration: TypedContractMethod<
    [_index: BigNumberish],
    [IFtsoInflationConfigurations.FtsoConfigurationStructOutput],
    "view"
  >;

  getFtsoConfigurations: TypedContractMethod<
    [],
    [IFtsoInflationConfigurations.FtsoConfigurationStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFtsoConfiguration"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [IFtsoInflationConfigurations.FtsoConfigurationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFtsoConfigurations"
  ): TypedContractMethod<
    [],
    [IFtsoInflationConfigurations.FtsoConfigurationStructOutput[]],
    "view"
  >;

  filters: {};
}
