/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IPChainVotePowerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchVotePowerOfAt"
      | "stakesOf"
      | "stakesOfAt"
      | "totalVotePower"
      | "totalVotePowerAt"
      | "totalVotePowerAtCached"
      | "votePowerFromTo"
      | "votePowerFromToAt"
      | "votePowerOf"
      | "votePowerOfAt"
      | "votePowerOfAtCached"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "VotePowerCacheCreated" | "VotePowerChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchVotePowerOfAt",
    values: [BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakesOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakesOfAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVotePower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVotePowerAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVotePowerAtCached",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerFromTo",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerFromToAt",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerOf",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerOfAt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerOfAtCached",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchVotePowerOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakesOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakesOfAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVotePower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVotePowerAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVotePowerAtCached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerFromTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerFromToAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerOfAtCached",
    data: BytesLike
  ): Result;
}

export namespace VotePowerCacheCreatedEvent {
  export type InputTuple = [nodeId: BytesLike, blockNumber: BigNumberish];
  export type OutputTuple = [nodeId: string, blockNumber: bigint];
  export interface OutputObject {
    nodeId: string;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotePowerChangedEvent {
  export type InputTuple = [
    owner: AddressLike,
    nodeId: BytesLike,
    priorVotePower: BigNumberish,
    newVotePower: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    nodeId: string,
    priorVotePower: bigint,
    newVotePower: bigint
  ];
  export interface OutputObject {
    owner: string;
    nodeId: string;
    priorVotePower: bigint;
    newVotePower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPChainVotePower extends BaseContract {
  connect(runner?: ContractRunner | null): IPChainVotePower;
  waitForDeployment(): Promise<this>;

  interface: IPChainVotePowerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchVotePowerOfAt: TypedContractMethod<
    [_nodeIds: BytesLike[], _blockNumber: BigNumberish],
    [bigint[]],
    "view"
  >;

  stakesOf: TypedContractMethod<
    [_owner: AddressLike],
    [[string[], bigint[]] & { _nodeIds: string[]; _amounts: bigint[] }],
    "view"
  >;

  stakesOfAt: TypedContractMethod<
    [_owner: AddressLike, _blockNumber: BigNumberish],
    [[string[], bigint[]] & { _nodeIds: string[]; _amounts: bigint[] }],
    "view"
  >;

  totalVotePower: TypedContractMethod<[], [bigint], "view">;

  totalVotePowerAt: TypedContractMethod<
    [_blockNumber: BigNumberish],
    [bigint],
    "view"
  >;

  totalVotePowerAtCached: TypedContractMethod<
    [_blockNumber: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  votePowerFromTo: TypedContractMethod<
    [_owner: AddressLike, _nodeId: BytesLike],
    [bigint],
    "view"
  >;

  votePowerFromToAt: TypedContractMethod<
    [_owner: AddressLike, _nodeId: BytesLike, _blockNumber: BigNumberish],
    [bigint],
    "view"
  >;

  votePowerOf: TypedContractMethod<[_nodeId: BytesLike], [bigint], "view">;

  votePowerOfAt: TypedContractMethod<
    [_nodeId: BytesLike, _blockNumber: BigNumberish],
    [bigint],
    "view"
  >;

  votePowerOfAtCached: TypedContractMethod<
    [_owner: BytesLike, _blockNumber: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchVotePowerOfAt"
  ): TypedContractMethod<
    [_nodeIds: BytesLike[], _blockNumber: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakesOf"
  ): TypedContractMethod<
    [_owner: AddressLike],
    [[string[], bigint[]] & { _nodeIds: string[]; _amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakesOfAt"
  ): TypedContractMethod<
    [_owner: AddressLike, _blockNumber: BigNumberish],
    [[string[], bigint[]] & { _nodeIds: string[]; _amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalVotePower"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVotePowerAt"
  ): TypedContractMethod<[_blockNumber: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVotePowerAtCached"
  ): TypedContractMethod<[_blockNumber: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "votePowerFromTo"
  ): TypedContractMethod<
    [_owner: AddressLike, _nodeId: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "votePowerFromToAt"
  ): TypedContractMethod<
    [_owner: AddressLike, _nodeId: BytesLike, _blockNumber: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "votePowerOf"
  ): TypedContractMethod<[_nodeId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "votePowerOfAt"
  ): TypedContractMethod<
    [_nodeId: BytesLike, _blockNumber: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "votePowerOfAtCached"
  ): TypedContractMethod<
    [_owner: BytesLike, _blockNumber: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "VotePowerCacheCreated"
  ): TypedContractEvent<
    VotePowerCacheCreatedEvent.InputTuple,
    VotePowerCacheCreatedEvent.OutputTuple,
    VotePowerCacheCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VotePowerChanged"
  ): TypedContractEvent<
    VotePowerChangedEvent.InputTuple,
    VotePowerChangedEvent.OutputTuple,
    VotePowerChangedEvent.OutputObject
  >;

  filters: {
    "VotePowerCacheCreated(bytes20,uint256)": TypedContractEvent<
      VotePowerCacheCreatedEvent.InputTuple,
      VotePowerCacheCreatedEvent.OutputTuple,
      VotePowerCacheCreatedEvent.OutputObject
    >;
    VotePowerCacheCreated: TypedContractEvent<
      VotePowerCacheCreatedEvent.InputTuple,
      VotePowerCacheCreatedEvent.OutputTuple,
      VotePowerCacheCreatedEvent.OutputObject
    >;

    "VotePowerChanged(address,bytes20,uint256,uint256)": TypedContractEvent<
      VotePowerChangedEvent.InputTuple,
      VotePowerChangedEvent.OutputTuple,
      VotePowerChangedEvent.OutputObject
    >;
    VotePowerChanged: TypedContractEvent<
      VotePowerChangedEvent.InputTuple,
      VotePowerChangedEvent.OutputTuple,
      VotePowerChangedEvent.OutputObject
    >;
  };
}
