/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfirmedBlockHeightExistsVerification,
  IConfirmedBlockHeightExistsVerificationInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IConfirmedBlockHeightExistsVerification";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "attestationType",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "sourceId",
                type: "bytes32",
              },
              {
                internalType: "uint64",
                name: "votingRound",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "lowestUsedTimestamp",
                type: "uint64",
              },
              {
                components: [
                  {
                    internalType: "uint64",
                    name: "blockNumber",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "queryWindow",
                    type: "uint64",
                  },
                ],
                internalType: "struct IConfirmedBlockHeightExists.RequestBody",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint64",
                    name: "blockTimestamp",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "numberOfConfirmations",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "lowestQueryWindowBlockNumber",
                    type: "uint64",
                  },
                  {
                    internalType: "uint64",
                    name: "lowestQueryWindowBlockTimestamp",
                    type: "uint64",
                  },
                ],
                internalType: "struct IConfirmedBlockHeightExists.ResponseBody",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IConfirmedBlockHeightExists.Response",
            name: "data",
            type: "tuple",
          },
        ],
        internalType: "struct IConfirmedBlockHeightExists.Proof",
        name: "_proof",
        type: "tuple",
      },
    ],
    name: "verifyConfirmedBlockHeightExists",
    outputs: [
      {
        internalType: "bool",
        name: "_proved",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConfirmedBlockHeightExistsVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IConfirmedBlockHeightExistsVerificationInterface {
    return new Interface(
      _abi
    ) as IConfirmedBlockHeightExistsVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfirmedBlockHeightExistsVerification {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IConfirmedBlockHeightExistsVerification;
  }
}
