/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDelegationAccount,
  IDelegationAccountInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IDelegationAccount";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "bips",
        type: "uint256",
      },
    ],
    name: "DelegateFtso",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "DelegateGovernance",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "executor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ExecutorFeePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ExternalTokenTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "contract IClaimSetupManager",
        name: "manager",
        type: "address",
      },
    ],
    name: "Initialize",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "RevokeFtso",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "UndelegateAllFtso",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "UndelegateGovernance",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawToOwner",
    type: "event",
  },
] as const;

export class IDelegationAccount__factory {
  static readonly abi = _abi;
  static createInterface(): IDelegationAccountInterface {
    return new Interface(_abi) as IDelegationAccountInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDelegationAccount {
    return new Contract(address, _abi, runner) as unknown as IDelegationAccount;
  }
}
