/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeCalculator,
  IFeeCalculatorInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IFeeCalculator";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes21[]",
        name: "_feedIds",
        type: "bytes21[]",
      },
    ],
    name: "calculateFeeByIds",
    outputs: [
      {
        internalType: "uint256",
        name: "_fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_indices",
        type: "uint256[]",
      },
    ],
    name: "calculateFeeByIndices",
    outputs: [
      {
        internalType: "uint256",
        name: "_fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFeeCalculator__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeCalculatorInterface {
    return new Interface(_abi) as IFeeCalculatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeCalculator {
    return new Contract(address, _abi, runner) as unknown as IFeeCalculator;
  }
}
