/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFtsoFeedPublisher,
  IFtsoFeedPublisherInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedPublisher";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "votingRoundId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "bytes21",
        name: "id",
        type: "bytes21",
      },
      {
        indexed: false,
        internalType: "int32",
        name: "value",
        type: "int32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "turnoutBIPS",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "int8",
        name: "decimals",
        type: "int8",
      },
    ],
    name: "FtsoFeedPublished",
    type: "event",
  },
  {
    inputs: [],
    name: "feedsHistorySize",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ftsoProtocolId",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "_feedId",
        type: "bytes21",
      },
    ],
    name: "getCurrentFeed",
    outputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "votingRoundId",
            type: "uint32",
          },
          {
            internalType: "bytes21",
            name: "id",
            type: "bytes21",
          },
          {
            internalType: "int32",
            name: "value",
            type: "int32",
          },
          {
            internalType: "uint16",
            name: "turnoutBIPS",
            type: "uint16",
          },
          {
            internalType: "int8",
            name: "decimals",
            type: "int8",
          },
        ],
        internalType: "struct IFtsoFeedPublisher.Feed",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "_feedId",
        type: "bytes21",
      },
      {
        internalType: "uint256",
        name: "_votingRoundId",
        type: "uint256",
      },
    ],
    name: "getFeed",
    outputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "votingRoundId",
            type: "uint32",
          },
          {
            internalType: "bytes21",
            name: "id",
            type: "bytes21",
          },
          {
            internalType: "int32",
            name: "value",
            type: "int32",
          },
          {
            internalType: "uint16",
            name: "turnoutBIPS",
            type: "uint16",
          },
          {
            internalType: "int8",
            name: "decimals",
            type: "int8",
          },
        ],
        internalType: "struct IFtsoFeedPublisher.Feed",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "uint32",
                name: "votingRoundId",
                type: "uint32",
              },
              {
                internalType: "bytes21",
                name: "id",
                type: "bytes21",
              },
              {
                internalType: "int32",
                name: "value",
                type: "int32",
              },
              {
                internalType: "uint16",
                name: "turnoutBIPS",
                type: "uint16",
              },
              {
                internalType: "int8",
                name: "decimals",
                type: "int8",
              },
            ],
            internalType: "struct IFtsoFeedPublisher.Feed",
            name: "body",
            type: "tuple",
          },
        ],
        internalType: "struct IFtsoFeedPublisher.FeedWithProof[]",
        name: "_proofs",
        type: "tuple[]",
      },
    ],
    name: "publish",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFtsoFeedPublisher__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoFeedPublisherInterface {
    return new Interface(_abi) as IFtsoFeedPublisherInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFtsoFeedPublisher {
    return new Contract(address, _abi, runner) as unknown as IFtsoFeedPublisher;
  }
}
