/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IValidatorRegistry,
  IValidatorRegistryInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/IValidatorRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dataProvider",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "nodeId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "pChainPublicKey",
        type: "string",
      },
    ],
    name: "DataProviderRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dataProvider",
        type: "address",
      },
    ],
    name: "DataProviderUnregistered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_nodeId",
        type: "bytes32",
      },
    ],
    name: "getDataProviderForNodeId",
    outputs: [
      {
        internalType: "address",
        name: "_dataProvider",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_pChainPublicKey",
        type: "bytes32",
      },
    ],
    name: "getDataProviderForPChainPublicKey",
    outputs: [
      {
        internalType: "address",
        name: "_dataProvider",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_dataProvider",
        type: "address",
      },
    ],
    name: "getDataProviderInfo",
    outputs: [
      {
        internalType: "string",
        name: "_nodeId",
        type: "string",
      },
      {
        internalType: "string",
        name: "_pChainPublicKey",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_nodeId",
        type: "string",
      },
      {
        internalType: "string",
        name: "_pChainPublicKey",
        type: "string",
      },
    ],
    name: "registerDataProvider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unregisterDataProvider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IValidatorRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IValidatorRegistryInterface {
    return new Interface(_abi) as IValidatorRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IValidatorRegistry {
    return new Contract(address, _abi, runner) as unknown as IValidatorRegistry;
  }
}
