/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RandomNumberV2Interface,
  RandomNumberV2InterfaceInterface,
} from "../../../../@flarenetwork/flare-periphery-contracts/coston2/RandomNumberV2Interface";

const _abi = [
  {
    inputs: [],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "_randomNumber",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_isSecureRandom",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "_randomTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_votingRoundId",
        type: "uint256",
      },
    ],
    name: "getRandomNumberHistorical",
    outputs: [
      {
        internalType: "uint256",
        name: "_randomNumber",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_isSecureRandom",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "_randomTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class RandomNumberV2Interface__factory {
  static readonly abi = _abi;
  static createInterface(): RandomNumberV2InterfaceInterface {
    return new Interface(_abi) as RandomNumberV2InterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RandomNumberV2Interface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RandomNumberV2Interface;
  }
}
