/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFtsoGenesis } from "./IFtsoGenesis";
export type { IFtsoManagerGenesis } from "./IFtsoManagerGenesis";
export type { IFtsoRegistryGenesis } from "./IFtsoRegistryGenesis";
